import { useNavigate, useParams } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout.jsx";
import { useProjects } from "../context/ProjectContext.jsx";

function ProjectDetails() {
  const { projectId } = useParams(); const navigate = useNavigate(); const { projects, tasks, members, projectProgress } = useProjects();
  const project = projects.find((item) => item.id === projectId);
  if (!project) return <DashboardLayout><div className="teamflow-page"><h2>Project not found</h2><button className="view-button" onClick={() => navigate("/projects")}>← Back to projects</button></div></DashboardLayout>;
  const projectTasks = tasks.filter((task) => task.projectId === project.id); const assignedIds = [...new Set(projectTasks.map((task) => task.assigneeId).filter(Boolean))]; const projectMembers = members.filter((member) => assignedIds.includes(member.id)); const progress = projectProgress(project.id);
  return <DashboardLayout><div className="teamflow-page project-detail-page"><button className="back-button" onClick={() => navigate("/projects")}>← All projects</button><section className="project-hero"><div><p className="welcome-label">PROJECT WORKSPACE</p><h2>{project.name}</h2><p>{project.description}</p><span className={`project-status ${project.status === "At Risk" ? "risk" : ""}`}>{project.status}</span></div><div className="hero-progress"><strong>{progress}%</strong><span>overall progress</span><div className="progress-background"><div className="progress-fill" style={{ width: `${progress}%` }} /></div></div></section><section className="project-summary"><article><small>Deadline</small><strong>{project.deadline}</strong></article><article><small>Team members</small><strong>{projectMembers.length}</strong></article><article><small>Total tasks</small><strong>{projectTasks.length}</strong></article><article><small>Open tasks</small><strong>{projectTasks.filter((task) => !task.assigneeId).length}</strong></article></section><section className="content-grid"><article className="panel"><div className="panel-header"><div><h3>Project brief</h3><p>The agreed direction for this work.</p></div></div><p className="requirement-copy">{project.requirements}</p></article><article className="panel"><div className="panel-header"><div><h3>Work snapshot</h3><p>What is happening now.</p></div><button className="view-button" onClick={() => navigate("/tasks")}>Open tasks →</button></div>{projectTasks.slice(0, 4).map((task) => <div className="snapshot-task" key={task.id}><span>{task.title}</span><span className={`task-status ${task.status.toLowerCase().replaceAll(" ", "-")}`}>{task.status}</span></div>)}</article></section><section className="panel team-table-panel"><div className="panel-header"><div><h3>Team progress</h3><p>See each person’s assigned work and completion level.</p></div></div><div className="table-container"><table><thead><tr><th>Member</th><th>Assigned work</th><th>Status</th><th>Progress</th></tr></thead><tbody>{projectMembers.map((member) => { const work = projectTasks.filter((task) => task.assigneeId === member.id); const memberProgress = work.length ? Math.round(work.reduce((sum, task) => sum + task.progress, 0) / work.length) : 0; return <tr key={member.id}><td><div className="table-member"><div className="member-avatar">{member.name.charAt(0)}</div><div><strong>{member.name}</strong><span>{member.role}</span></div></div></td><td>{work.map((task) => task.title).join(", ")}</td><td><span className="task-status in-progress">{work.some((task) => task.status === "In Progress") ? "In progress" : work[0]?.status}</span></td><td><div className="table-progress"><div className="progress-background"><div className="progress-fill" style={{ width: `${memberProgress}%` }} /></div><span>{memberProgress}%</span></div></td></tr>; })}</tbody></table></div></section></div></DashboardLayout>;
}
export default ProjectDetails;
